### ISSUE TITLE
Server is not showing in masterserver.

### ISSUE THREAD

**Issue by tyabus** [rtcwcoop/rtcwcoop#11]
my cfg is 
set sv_hostname "Barys RTCW"
set sv_maxcoopclients "16"
set net_port 10654
set net_address 0.0.0.0
set g_skipcutscenes 1
set g_maxlives 0
set g_gameskill 2
set g_friendlyfire 0
coopmap escape1

**Comment by zturtleman** [comment]
Did you start the server using `rtcwcoopded +set dedicated 2` ?

**Comment by tyabus** [comment]
Thanks.
