### ISSUE TITLE
ui/menus.txt

### ISSUE THREAD

**Issue by WildWolfReal** [rtcwcoop/rtcwcoop#12]
I can create a server but when my friend tries to join my game or the opposite way around we get this issue   

> **default menu file not found:** ui/menus.txt, unable to  continue!

What can I do because I am going to have a sleepover and I would like to play rtcw coop with my friend.
Thanks in advance.
@zturtleman 
@MAN-AT-ARMS 
@fretn

**Comment by MAN-AT-ARMS** [comment]
What files do you have in the 'main' folder?

**Comment by WildWolfReal** [comment]
Here's a link to what I have in the ''Main'' folder, I took a Print Screen and posted it on Imgur https://imgur.com/a/eKV9K  @MAN-AT-ARMS

**Comment by WildWolfReal** [comment]
Don't bother answering my question I fixed it. The issue was that I had a different version of wolfenstein on my old computer. 
Thank you for helping me can't wait to beat the game with a friend. Cheers mate.

**Comment by MAN-AT-ARMS** [comment]
Sounds good. Have fun.
