### ISSUE TITLE
Taking screenshots in menu (probably) crash

### ISSUE THREAD

**Issue by zturtleman** [rtcwcoop/rtcwcoop#33]
After https://github.com/rtcwcoop/rtcwcoop/commit/9613790f5a8d99f8acce7228f8dc1db9bd3ce92a if tr.world is NULL (such as in main menu) when a screenshot is taken the game will crash. (I haven't actually tested this.)

**Comment by Duk0** [comment]
You are right I tested it. I hadn't thought of it.
