### ISSUE TITLE
Problem with ui_coop_x86.dll

### ISSUE THREAD

**Issue by mihalicyn** [rtcwcoop/rtcwcoop#47]
Hello, friends,

First of all, I would like to say thanks to the team of this great and fantastic project :)

About problem...
My friend noticed, that on Linux there is a problem with maplist in menu - maplist is empty.
On Windows (using Cygwin) problem not appears. All works just fine. After lot of debugging, and trying to find place in code (I've studied the code under Windows), where menu is forming, I've realized, that problem is that game not loads actual file `<game directory>/coopmain/ui_coop_x86.dll`. Instead of that, game uses `ui_coop_x86.dll` file from bin.pk3 file. After that discovery, I've tried to remove `bin.pk3` file at all, and place `ui_coop_x86.dll` that I've compiled from sources to `<game directory>/coopmain/ui_coop_x86.dll`. After that problem is appeared under Windows! Then, I've tried to replace compiled `ui_coop_x86.dll` with version of that library from bin.pk3 that I've unpacked manually. And all started to work as needed!
Problem is, that, version of file `ui_coop_x86.dll` that produces after compilation from sources is not correct and seriously differs with version in `bin.pk3` archive.

Thanks
Regards, Alex

**Comment by MAN-AT-ARMS** [comment]
The dll in the bin.pk3 file is the 2.0.2 release version and is only used when connecting to servers with "Pure" enabled. This is used to enforce all players are using the same version on an internet server, etc.

Compiled dll's are going to differ based on code updates since release, compiler, platform, etc.

**Comment by mihalicyn** [comment]
@MAN-AT-ARMS thank you for fast reply! ;)
Where I can get source code to compile version of `ui_coop_x86` that provided in `bin.pk3`?
