### ISSUE TITLE
How to run server on linux?

### ISSUE THREAD

**Issue by lnesuper** [rtcwcoop/rtcwcoop#56]
Run a server on Linux, how to ? think!

**Comment by fretn** [comment]
run the rtcwcoopded.x86_64 file or rtcwcoopded.x86 (if you are on a 32bit linux) and check the wiki to see the possible command line arguments.

example:

```./rtcwcoopded.x86_64 +coopmap escape1```

**Comment by lnesuper** [comment]
> 
> 
> run the rtcwcoopded.x86_64 file or rtcwcoopded.x86 (if you are on a 32bit linux) and check the wiki to see the possible command line arguments.
> 
> example:
> 
> `./rtcwcoopded.x86_64 +coopmap escape1`

thinks you, it is work!
