### ISSUE TITLE
Raspberry pi 3 b Compilation Issue

### ISSUE THREAD

**Issue by Lonely-Dark** [rtcwcoop/rtcwcoop#58]
Hello, i try compile rtcwcoop in my raspberry pi, but i got this error:
`make[2]: *** No rule to make target 'build/release-linux-arm/ded/vm_armv7l.o', needed by 'build/release-linux-arm/rtcwcoopded.arm'.  Stop.`

I have done through guide README_RASPBERRYPI
Thanks

**Comment by MAN-AT-ARMS** [comment]
There was a file missing from the repository if you want to repull and try again.
On newer distributions you should just be able to type 'make' to build

**Comment by Lonely-Dark** [comment]
Thanks a lot. Issue closed.
