### ISSUE TITLE
Building RTCWCoop on NetBSD will give me the solo game menu

### ISSUE THREAD

**Issue by Adrien2002** [rtcwcoop/rtcwcoop#6]
I built RTCWCoop simply using "gmake" in the source directory and when I try to launch the game, here is what I'll have http://i.imgur.com/VZDXOj1.jpg

Here is the entire output

> RTCWCoop 1.0.2_GIT_c480985-2016-11-21 netbsd-amd64 Jun 15 2017
> Have SSE support
> ----- FS_Startup -----
> Current search path:
> /home/Adrien2002/.wolf/coopmain
> /home/Adrien2002/.wolf/main
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/coopmain
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/sp_pak4.pk3 (21 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/sp_pak3.pk3 (14 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/sp_pak2.pk3 (232 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/sp_pak1.pk3 (1342 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/pak0.pk3 (4775 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pakmaps6.pk3 (81 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pakmaps5.pk3 (35 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pakmaps4.pk3 (52 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pakmaps3.pk3 (83 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pakmaps2.pk3 (47 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pakmaps1.pk3 (34 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pakmaps0.pk3 (21 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pak5.pk3 (77 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pak4.pk3 (5 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pak3.pk3 (76 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pak2.pk3 (3 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pak1.pk3 (308 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_pak0.pk3 (783 files)
> /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/main/mp_bin.pk3 (4 files)
> 
> ----------------------
> 7993 files in pk3 files
> execing default.cfg
> execing wolfconfig.coop.cfg
> couldn't exec autoexec.coop.cfg
> Hunk_Clear: reset the hunk ok
> Bypassing CD checks
> logfile opened on Thu Jun 15 14:45:31 2017
> 
> ----- Client Initialization -----
> Couldn't read rtcwhistory.
> ----- Initializing Renderer ----
> Trying to load "renderer_coop_opengl1_amd64.so" from "/home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop"...
> -------------------------------
> RTCWKEY found.
> ----- Client Initialization Complete -----
> ----- R_Init -----
> SDL using driver "x11"
> Initializing OpenGL display
> Display aspect: 1.778
> ...setting mode 3: 640 480
> Using 24 color bits, 24 depth, 0 stencil display.
> Available modes: '1280x720 1920x1080 720x480 640x480 800x600 1024x768 720x576 1280x1024 1440x576 1440x480'
> GL_RENDERER: Gallium 0.4 on AMD OLAND (DRM 2.38.0, LLVM 3.8.1)
> Initializing OpenGL extensions
> ...GL_EXT_texture_compression_s3tc not found
> ...GL_S3_s3tc not found
> ...using GL_EXT_texture_env_add
> ...using GL_ARB_multitexture
> ...using GL_EXT_compiled_vertex_array
> ...ignoring GL_EXT_texture_filter_anisotropic
> Initializing Shaders
> ^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
> ^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
> ----- finished R_Init -----
> ------ Initializing Sound ------
> Trying to load "libopenal.so.1"...
> Allocated 128 sources.
> OpenAL default capture device is 'OSS Default'
> OpenAL capture device opened.
> OpenAL info:
>   Vendor:         OpenAL Community
>   Version:        1.1 ALSOFT 1.17.2
>   Renderer:       OpenAL Soft
>   AL Extensions:  AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
>   ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFTX_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_pause_device
>   Device:         OSS Default
>   Available Devices:
> OSS Default
>   Input Device:   OSS Default
>   Available Input Devices:
> OSS Default
> Sound initialization successful.
> --------------------------------
> Try loading dll file /home/Adrien2002/Programmes/Return to Castle Wolfenstein Coop/coopmain/ui.coop.amd64.so
> ^1menu file not found: coopgameinfo.txt, using default
> ^3WARNING: R_FindImageFileExt could not find 'ui_mp/assets/notebook1.tga' in shader 'notebook1'
> ^3Shader notebook1 has a stage with no image
> --- Common Initialization Complete ---
> IP: 127.0.0.1
> IP6: ::1
> IP6: fe80:1::1
> IP6: fe80:2::ca60:ff:fee2:266b
> IP: 192.168.1.18
> IP6: 2a01:e34:edb8:33a0:66eb:920f:8e5e:7d7f
> Opening IP6 socket: [::]:27960
> Opening IP socket: 0.0.0.0:27960
> ^3turning EXEC_NOW 'quit' into EXEC_INSERT
> ----- Client Shutdown (Client quit) -----
> RE_Shutdown( 1 )
> Hunk_Clear: reset the hunk ok
> OpenAL capture device closed.
> -----------------------

By the way, out of topic but why not to add, in the code, to look for "Main" if "main" doesn't exist or if *pk3 files aren't found in "main" folder since the latest official build of RTCW you can find on GOG is using "Main" to hold all *pk3 files

**Comment by MAN-AT-ARMS** [comment]
You're missing the sp_pak_coop.pk3 file
There are create_pk3.sh scripts in the root of the repository to create it (thoguh won't work for you because architecture is named amd64 on BSD.

You need to go into media / sp_pak_coop1 folder, zip up the contents, and copy to the coopmain folder.

ie....
cd media/sp_pak_coop1
zip -ru sp_pak_coop1.pk3 *

**Comment by MAN-AT-ARMS** [comment]
It will get GOG support eventually when I sync up with latest iortcw engine.
Any of the coop only stuff belongs in the coopmain folder so it doesn't interfere with the vanilla game.

**Comment by Adrien2002** [comment]
It worked !
Thank you very much for that :)
