### ISSUE TITLE
GLES/gl.h: No such file or directory

### ISSUE THREAD

**Issue by CorsaXTD** [rtcwcoop/rtcwcoop#64]
Was compiling fine until it gave another error. :(
In file included from code/renderer/qgl.h:38,
                 from code/renderer/tr_local.h:37,
                 from code/renderer/tr_altivec.c:29:
/usr/local/include/SDL2/SDL_opengles.h:32:10: fatal error: GLES/gl.h: No such file or directory
 #include <GLES/gl.h>
          ^~~~~~~~~~~
compilation terminated.

**Comment by fretn** [comment]
you're probably missing another dependency or the following post might help you out:

https://raspberrypi.stackexchange.com/questions/27523/how-to-use-opengl-via-sdl2

**Comment by CorsaXTD** [comment]
Thanks, it helped. Was libgles2 and libgles-dev missing.
